//
// LibraryStructureAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import AnyCodable
import Foundation
import PromiseKit

open class LibraryStructureAPI {
    /**
     Add a media path to a library.
     
     - parameter mediaPathDto: (body) The media path dto. 
     - parameter refreshLibrary: (query) Whether to refresh the library. (optional, default to false)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<Void>
     */
    open class func addMediaPath( mediaPathDto: MediaPathDto,  refreshLibrary: Bool? = nil, apiResponseQueue: DispatchQueue = JellyfinAPI.apiResponseQueue) -> Promise<Void> {
        let deferred = Promise<Void>.pending()
        addMediaPathWithRequestBuilder(mediaPathDto: mediaPathDto, refreshLibrary: refreshLibrary).execute(apiResponseQueue) { result -> Void in
            switch result {
            case .success:
                deferred.resolver.fulfill(())
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Add a media path to a library.
     - POST /Library/VirtualFolders/Paths
     - API Key:
       - type: apiKey X-Emby-Authorization 
       - name: CustomAuthentication
     - parameter mediaPathDto: (body) The media path dto. 
     - parameter refreshLibrary: (query) Whether to refresh the library. (optional, default to false)
     - returns: RequestBuilder<Void> 
     */
    open class func addMediaPathWithRequestBuilder(mediaPathDto: MediaPathDto, refreshLibrary: Bool? = nil) -> RequestBuilder<Void> {
        let urlPath = "/Library/VirtualFolders/Paths"
        let URLString = JellyfinAPI.basePath + urlPath
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: mediaPathDto)

        var urlComponents = URLComponents(string: URLString)
        urlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "refreshLibrary": refreshLibrary?.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = JellyfinAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Adds a virtual folder.
     
     - parameter name: (query) The name of the virtual folder. (optional)
     - parameter collectionType: (query) The type of the collection. (optional)
     - parameter paths: (query) The paths of the virtual folder. (optional)
     - parameter refreshLibrary: (query) Whether to refresh the library. (optional, default to false)
     - parameter addVirtualFolderDto: (body) The library options. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<Void>
     */
    open class func addVirtualFolder( name: String? = nil,  collectionType: CollectionTypeOptions? = nil,  paths: [String]? = nil,  refreshLibrary: Bool? = nil,  addVirtualFolderDto: AddVirtualFolderDto? = nil, apiResponseQueue: DispatchQueue = JellyfinAPI.apiResponseQueue) -> Promise<Void> {
        let deferred = Promise<Void>.pending()
        addVirtualFolderWithRequestBuilder(name: name, collectionType: collectionType, paths: paths, refreshLibrary: refreshLibrary, addVirtualFolderDto: addVirtualFolderDto).execute(apiResponseQueue) { result -> Void in
            switch result {
            case .success:
                deferred.resolver.fulfill(())
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Adds a virtual folder.
     - POST /Library/VirtualFolders
     - API Key:
       - type: apiKey X-Emby-Authorization 
       - name: CustomAuthentication
     - parameter name: (query) The name of the virtual folder. (optional)
     - parameter collectionType: (query) The type of the collection. (optional)
     - parameter paths: (query) The paths of the virtual folder. (optional)
     - parameter refreshLibrary: (query) Whether to refresh the library. (optional, default to false)
     - parameter addVirtualFolderDto: (body) The library options. (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func addVirtualFolderWithRequestBuilder(name: String? = nil, collectionType: CollectionTypeOptions? = nil, paths: [String]? = nil, refreshLibrary: Bool? = nil, addVirtualFolderDto: AddVirtualFolderDto? = nil) -> RequestBuilder<Void> {
        let urlPath = "/Library/VirtualFolders"
        let URLString = JellyfinAPI.basePath + urlPath
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: addVirtualFolderDto)

        var urlComponents = URLComponents(string: URLString)
        urlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "name": name?.encodeToJSON(),
            "collectionType": collectionType?.encodeToJSON(),
            "paths": paths?.encodeToJSON(),
            "refreshLibrary": refreshLibrary?.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = JellyfinAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Gets all virtual folders.
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<[VirtualFolderInfo]>
     */
    open class func getVirtualFolders(apiResponseQueue: DispatchQueue = JellyfinAPI.apiResponseQueue) -> Promise<[VirtualFolderInfo]> {
        let deferred = Promise<[VirtualFolderInfo]>.pending()
        getVirtualFoldersWithRequestBuilder().execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Gets all virtual folders.
     - GET /Library/VirtualFolders
     - API Key:
       - type: apiKey X-Emby-Authorization 
       - name: CustomAuthentication
     - returns: RequestBuilder<[VirtualFolderInfo]> 
     */
    open class func getVirtualFoldersWithRequestBuilder() -> RequestBuilder<[VirtualFolderInfo]> {
        let urlPath = "/Library/VirtualFolders"
        let URLString = JellyfinAPI.basePath + urlPath
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[VirtualFolderInfo]>.Type = JellyfinAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Remove a media path.
     
     - parameter name: (query) The name of the library. (optional)
     - parameter path: (query) The path to remove. (optional)
     - parameter refreshLibrary: (query) Whether to refresh the library. (optional, default to false)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<Void>
     */
    open class func removeMediaPath( name: String? = nil,  path: String? = nil,  refreshLibrary: Bool? = nil, apiResponseQueue: DispatchQueue = JellyfinAPI.apiResponseQueue) -> Promise<Void> {
        let deferred = Promise<Void>.pending()
        removeMediaPathWithRequestBuilder(name: name, path: path, refreshLibrary: refreshLibrary).execute(apiResponseQueue) { result -> Void in
            switch result {
            case .success:
                deferred.resolver.fulfill(())
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Remove a media path.
     - DELETE /Library/VirtualFolders/Paths
     - API Key:
       - type: apiKey X-Emby-Authorization 
       - name: CustomAuthentication
     - parameter name: (query) The name of the library. (optional)
     - parameter path: (query) The path to remove. (optional)
     - parameter refreshLibrary: (query) Whether to refresh the library. (optional, default to false)
     - returns: RequestBuilder<Void> 
     */
    open class func removeMediaPathWithRequestBuilder(name: String? = nil, path: String? = nil, refreshLibrary: Bool? = nil) -> RequestBuilder<Void> {
        let urlPath = "/Library/VirtualFolders/Paths"
        let URLString = JellyfinAPI.basePath + urlPath
        let parameters: [String: Any]? = nil

        var urlComponents = URLComponents(string: URLString)
        urlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "name": name?.encodeToJSON(),
            "path": path?.encodeToJSON(),
            "refreshLibrary": refreshLibrary?.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = JellyfinAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Removes a virtual folder.
     
     - parameter name: (query) The name of the folder. (optional)
     - parameter refreshLibrary: (query) Whether to refresh the library. (optional, default to false)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<Void>
     */
    open class func removeVirtualFolder( name: String? = nil,  refreshLibrary: Bool? = nil, apiResponseQueue: DispatchQueue = JellyfinAPI.apiResponseQueue) -> Promise<Void> {
        let deferred = Promise<Void>.pending()
        removeVirtualFolderWithRequestBuilder(name: name, refreshLibrary: refreshLibrary).execute(apiResponseQueue) { result -> Void in
            switch result {
            case .success:
                deferred.resolver.fulfill(())
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Removes a virtual folder.
     - DELETE /Library/VirtualFolders
     - API Key:
       - type: apiKey X-Emby-Authorization 
       - name: CustomAuthentication
     - parameter name: (query) The name of the folder. (optional)
     - parameter refreshLibrary: (query) Whether to refresh the library. (optional, default to false)
     - returns: RequestBuilder<Void> 
     */
    open class func removeVirtualFolderWithRequestBuilder(name: String? = nil, refreshLibrary: Bool? = nil) -> RequestBuilder<Void> {
        let urlPath = "/Library/VirtualFolders"
        let URLString = JellyfinAPI.basePath + urlPath
        let parameters: [String: Any]? = nil

        var urlComponents = URLComponents(string: URLString)
        urlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "name": name?.encodeToJSON(),
            "refreshLibrary": refreshLibrary?.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = JellyfinAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Renames a virtual folder.
     
     - parameter name: (query) The name of the virtual folder. (optional)
     - parameter newName: (query) The new name. (optional)
     - parameter refreshLibrary: (query) Whether to refresh the library. (optional, default to false)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<Void>
     */
    open class func renameVirtualFolder( name: String? = nil,  newName: String? = nil,  refreshLibrary: Bool? = nil, apiResponseQueue: DispatchQueue = JellyfinAPI.apiResponseQueue) -> Promise<Void> {
        let deferred = Promise<Void>.pending()
        renameVirtualFolderWithRequestBuilder(name: name, newName: newName, refreshLibrary: refreshLibrary).execute(apiResponseQueue) { result -> Void in
            switch result {
            case .success:
                deferred.resolver.fulfill(())
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Renames a virtual folder.
     - POST /Library/VirtualFolders/Name
     - API Key:
       - type: apiKey X-Emby-Authorization 
       - name: CustomAuthentication
     - parameter name: (query) The name of the virtual folder. (optional)
     - parameter newName: (query) The new name. (optional)
     - parameter refreshLibrary: (query) Whether to refresh the library. (optional, default to false)
     - returns: RequestBuilder<Void> 
     */
    open class func renameVirtualFolderWithRequestBuilder(name: String? = nil, newName: String? = nil, refreshLibrary: Bool? = nil) -> RequestBuilder<Void> {
        let urlPath = "/Library/VirtualFolders/Name"
        let URLString = JellyfinAPI.basePath + urlPath
        let parameters: [String: Any]? = nil

        var urlComponents = URLComponents(string: URLString)
        urlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "name": name?.encodeToJSON(),
            "newName": newName?.encodeToJSON(),
            "refreshLibrary": refreshLibrary?.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = JellyfinAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Update library options.
     
     - parameter updateLibraryOptionsDto: (body) The library name and options. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<Void>
     */
    open class func updateLibraryOptions( updateLibraryOptionsDto: UpdateLibraryOptionsDto? = nil, apiResponseQueue: DispatchQueue = JellyfinAPI.apiResponseQueue) -> Promise<Void> {
        let deferred = Promise<Void>.pending()
        updateLibraryOptionsWithRequestBuilder(updateLibraryOptionsDto: updateLibraryOptionsDto).execute(apiResponseQueue) { result -> Void in
            switch result {
            case .success:
                deferred.resolver.fulfill(())
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Update library options.
     - POST /Library/VirtualFolders/LibraryOptions
     - API Key:
       - type: apiKey X-Emby-Authorization 
       - name: CustomAuthentication
     - parameter updateLibraryOptionsDto: (body) The library name and options. (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func updateLibraryOptionsWithRequestBuilder(updateLibraryOptionsDto: UpdateLibraryOptionsDto? = nil) -> RequestBuilder<Void> {
        let urlPath = "/Library/VirtualFolders/LibraryOptions"
        let URLString = JellyfinAPI.basePath + urlPath
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateLibraryOptionsDto)

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = JellyfinAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Updates a media path.
     
     - parameter updateMediaPathRequestDto: (body) The name of the library and path infos. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<Void>
     */
    open class func updateMediaPath( updateMediaPathRequestDto: UpdateMediaPathRequestDto, apiResponseQueue: DispatchQueue = JellyfinAPI.apiResponseQueue) -> Promise<Void> {
        let deferred = Promise<Void>.pending()
        updateMediaPathWithRequestBuilder(updateMediaPathRequestDto: updateMediaPathRequestDto).execute(apiResponseQueue) { result -> Void in
            switch result {
            case .success:
                deferred.resolver.fulfill(())
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Updates a media path.
     - POST /Library/VirtualFolders/Paths/Update
     - API Key:
       - type: apiKey X-Emby-Authorization 
       - name: CustomAuthentication
     - parameter updateMediaPathRequestDto: (body) The name of the library and path infos. 
     - returns: RequestBuilder<Void> 
     */
    open class func updateMediaPathWithRequestBuilder(updateMediaPathRequestDto: UpdateMediaPathRequestDto) -> RequestBuilder<Void> {
        let urlPath = "/Library/VirtualFolders/Paths/Update"
        let URLString = JellyfinAPI.basePath + urlPath
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateMediaPathRequestDto)

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = JellyfinAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

}
