//
// TimeSyncAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import AnyCodable
import Foundation
import PromiseKit

open class TimeSyncAPI {
    /**
     Gets the current UTC time.
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<UtcTimeResponse>
     */
    open class func getUtcTime(apiResponseQueue: DispatchQueue = JellyfinAPI.apiResponseQueue) -> Promise<UtcTimeResponse> {
        let deferred = Promise<UtcTimeResponse>.pending()
        getUtcTimeWithRequestBuilder().execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Gets the current UTC time.
     - GET /GetUtcTime
     - returns: RequestBuilder<UtcTimeResponse> 
     */
    open class func getUtcTimeWithRequestBuilder() -> RequestBuilder<UtcTimeResponse> {
        let urlPath = "/GetUtcTime"
        let URLString = JellyfinAPI.basePath + urlPath
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<UtcTimeResponse>.Type = JellyfinAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

}
